### ISSUE TITLE
Feature request: Add "copy to clipboard" button [ADDED]

### ISSUE THREAD

**Issue by moigagoo** [molnarmark/nimism.co#1]
Next to the "nimble install" line:

![](https://i.imgur.com/JwNleaE.png)

**Comment by molnarmark** [comment]
This was [added](https://github.com/molnarmark/nimism.co/commit/1586d45a332888afb8ec61e883b039491d7753df).
I was also thinking about adding tooltips, but im not entirely sure if i like them.
![60ef260ef260ef2](https://cloud.githubusercontent.com/assets/13263073/24546806/3b5601ac-160d-11e7-8823-008ebe50939d.png)

**Comment by moigagoo** [comment]
God that was fast :-)
